### ISSUE TITLE
CollectInt method name implies collecting an integer; however contains logic to check if 0.

### ISSUE THREAD

**Issue by steve-warren** [trentonhicks/AddressBook#22]
https://github.com/trentonhicks/AddressBook/blob/fbbf174869fe60d7c37cba6a6a1a380e8f3fe0c7/AddressBook/AddressBook/Collect.cs#L67-L75

Appears menu logic is included in this method. Either rename method to explain it's function or move logic checking for 0 out to the code calling this method.

**Comment by EvanNettleton** [comment]
Reviewed code and found the method not being used. I deleted the code and verified if it broke anything.
