### ISSUE TITLE
CaptureID parses an integer, not an ID

### ISSUE THREAD

**Issue by steve-warren** [trentonhicks/AddressBook#23]
https://github.com/trentonhicks/AddressBook/blob/fbbf174869fe60d7c37cba6a6a1a380e8f3fe0c7/AddressBook/AddressBook/Collect.cs#L91-L110

It's name implies it is collecting ID; however it is parsing a string into an integer. Consider renaming this method.

**Comment by EvanNettleton** [comment]
I changed the method name to CollectUserSelection
