### ISSUE TITLE
Retrieval of a Single Contact

### ISSUE THREAD

**Issue by steve-warren** [trentonhicks/AddressBook#5]
https://github.com/trentonhicks/AddressBook/blob/fbbf174869fe60d7c37cba6a6a1a380e8f3fe0c7/AddressBook/AddressBook/SQL.cs#L231

Instead of retrieving all contacts from the database and enumerating them in memory, create a separate method that queries the database for a single user.

**Comment by Daniel-Figueroa** [comment]
Changed now just need to test it
